# Database connection settings

spring.datasource.url = jdbc:postgresql://localhost:5432/finance_app
spring.datasource.username = postgres
spring.datasource.password = vedant2840

# Hibernate properties

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# JWT properties
jwt.secret=VaultAnalyticsSuperSecretKeyForJWTSigning123456

# Token Lifetime Expiration Window (24 Hours in milliseconds = 86,400,000 ms)
jwt.expiration=86400000


