# Database connection settings

spring.datasource.url = jdbc:postgresql://localhost:5432/finance_app
spring.datasource.username = postgres
spring.datasource.password = vedant2840

# Hibernate properties

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# JWT properties
jwt.secret=VaultAnalyticsSuperSecretKeyForJWTSigning123456

# Token Lifetime Expiration Window (24 Hours in milliseconds = 86,400,000 ms)
jwt.expiration=86400000


# =================================================================
# ? FREE GMAIL SMTP CONFIGURATION
# =================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:vedantpatel@gecg28.ac.in}
spring.mail.password=${MAIL_PASSWORD:oyppoquwjobxasjz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000